language: node_js
node_js:
 - "4.1"
addons:
 - firefox: "38.0"
before_install:
# Setup Chrome
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
install:
 - npm install -g npm
 - npm install -g gulp
 - npm install -g bower
 - npm install
 - bower install
script:
 - gulp test
before_deploy:
 - gulp build -d
